### PR TITLE
Add: append_text_chunk method

### PR DESCRIPTION
**Pull request by bburns**
Thanks for this library! 

I needed to be able to add tEXt chunks to an APNG file, so added this method - I've used it with UPNG.js on the other end and it works okay.

### CODE REVIEW

**Comment by eight04** [comment]
It's a good idea to allow users to add additional information to an APNG file. About the code:

* `append_text_chunk` method shouldn't be implemented in `APNG` class. `APNG` is just a container of multiple PNGs. 
* The creation of the `tEXt` chunk should be decoupled.
* We should support different types of text chunks.

I would expect something like this:
```py
from apng import APNG, make_text_chunk

im = APNG.open("file.png")
png, control = im.frames[0]
png.chunks.append(make_text_chunk(type="tEXt", key="Comment", data="some text"))
im.save("file.png")
```
Also, we need a `Chunk` class/namedtuple to represent the chunk.

**Comment by bburns** [comment]
Okay, I made a preliminary `create_text_chunk`, but not any `parse_chunks` code. This is not tested. 

I won't be able to get back to this for a while, but might be a starting point for someone else to complete the corresponding  `parse_chunks` code.

**Comment by eight04** [comment]
I'll complete the rest later.

**Comment by bburns** [comment]
Thanks for implementing this! Will come in handy.

**Pull request merged**
